{
'useTabs': false,
'tabWidth': 2,
'semi': true,
'singleQuote': true
'printWidth': 100,
'arrowParens': always,
'trailingComma': es5,
'endOfLine': lf,
'insertFinalNewline': true,
'singleAttributePerLine ': true
}
